version: "3.2"
services:
  backend:
    build:
      context: ..
      dockerfile: ./deploy/docker/Dockerfile
    container_name: ohlc-data-api
    env_file: ../.env
    volumes:
      - ./media/uploads
      - ohlc-data:/media/uploads
    networks:
      ohlc-api-network:
    depends_on:
      - postgresql
    ports:
      - "3000:3000"

  postgresql:
    image: postgres
    container_name: ohlc-postgres
    ports:
      - "5400:5432"
    env_file: ../.env
    volumes:
      - ./scripts/db/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ohlc-data:/var/lib/postgresql/data
    restart: always
    networks:
      ohlc-api-network:
        aliases:
          - ohlc-postgres

networks:
  ohlc-api-network: null
volumes:
  ohlc-data: null
